// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4I7MLfvKWMf8h6OPxTAJkgzHXQKF5kgs',
    appId: '1:900549720926:web:f4838c76e8a363ea31edcf',
    messagingSenderId: '900549720926',
    projectId: 'dummyjson-e794f',
    authDomain: 'dummyjson-e794f.firebaseapp.com',
    storageBucket: 'dummyjson-e794f.firebasestorage.app',
    measurementId: 'G-X3LVRCVC5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqqcz6LLrYB3lJ4q9JL02c7Apjl7-PZ3k',
    appId: '1:900549720926:android:dfaf2ea03c8f425031edcf',
    messagingSenderId: '900549720926',
    projectId: 'dummyjson-e794f',
    storageBucket: 'dummyjson-e794f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApujMiXZynRQKT7PwA44OwYmzvfN1rXf0',
    appId: '1:900549720926:ios:bb1f67c63e31c88631edcf',
    messagingSenderId: '900549720926',
    projectId: 'dummyjson-e794f',
    storageBucket: 'dummyjson-e794f.firebasestorage.app',
    iosBundleId: 'com.example.dummyjson',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApujMiXZynRQKT7PwA44OwYmzvfN1rXf0',
    appId: '1:900549720926:ios:bb1f67c63e31c88631edcf',
    messagingSenderId: '900549720926',
    projectId: 'dummyjson-e794f',
    storageBucket: 'dummyjson-e794f.firebasestorage.app',
    iosBundleId: 'com.example.dummyjson',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4I7MLfvKWMf8h6OPxTAJkgzHXQKF5kgs',
    appId: '1:900549720926:web:2547dcad26e7787331edcf',
    messagingSenderId: '900549720926',
    projectId: 'dummyjson-e794f',
    authDomain: 'dummyjson-e794f.firebaseapp.com',
    storageBucket: 'dummyjson-e794f.firebasestorage.app',
    measurementId: 'G-ZW6EKH95K7',
  );
}
